import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function exportAQIReport(data) {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(22);
  doc.setTextColor(0, 170, 255);
  doc.text("AQ Analytics", 15, 20);

  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text("Air Quality Report", 15, 30);

  // Date
  doc.setFontSize(11);
  doc.setTextColor(100);

  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    15,
    40
  );

  // -----------------------
  // Current Status
  // -----------------------

  autoTable(doc, {
    startY: 50,
    head: [["Current Environmental Status", ""]],
    body: [
      ["Location", data.city],
      ["AQI", `${data.aqi_index} (${data.status})`],
      ["Temperature", `${data.temperature} °C`],
      ["Humidity", `${data.humidity}%`],
      ["Wind Speed", `${data.wind_speed} m/s`],
    ],
    theme: "grid",
    headStyles: {
      fillColor: [0, 180, 255],
    },
  });

  // -----------------------
  // Pollutants
  // -----------------------

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 10,
    head: [["Pollutant", "Value"]],
    body: [
      ["PM2.5", data.pm2_5],
      ["PM10", data.pm10],
      ["NO₂", data.no2],
      ["O₃", data.o3],
      ["CO", data.co],
    ],
    theme: "striped",
    headStyles: {
      fillColor: [30, 144, 255],
    },
  });

  // -----------------------
  // Forecast
  // -----------------------

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 10,
    head: [["Date", "Temperature"]],
    body: data.forecast.map((item) => [
      item.day,
      `${item.temp} °C`,
    ]),
    theme: "grid",
    headStyles: {
      fillColor: [0, 200, 150],
    },
  });

  // Footer

  doc.setFontSize(10);

  doc.setTextColor(120);

  doc.text(
    "Generated by AQ Analytics Dashboard",
    15,
    285
  );

  doc.save(
    `AQ_Report_${new Date()
      .toISOString()
      .slice(0, 10)}.pdf`
  );
}